### ISSUE TITLE
geopandas vs geopandas-base dependency

### ISSUE THREAD

**Issue by H-Plus-Time** [conda-forge/dask-geopandas-feedstock#4]
Aside from fiona, geopandas-base has all the dependencies required for dask-geopandas. Would it be preferable to drop the dependency down to geopandas-base for the suffix-free package (and ensure fiona is in the dep list), or publish a minimal version under dask-geopandas-base?

**Comment by jorisvandenbossche** [comment]
Yes, we should use `geopandas-base` here, thanks for bringing this up (I suppose this is from before we had that base package). Especially since we don't even use fiona in dask-geopandas. 

I don't think we need to add extra dependencies to the list. If we people want the full dependency list of `geopandas`, they can install both `conda install geopandas dask-geopandas`? (and then just `conda install dask-geopandas` only gives you the limited set of dependencies)
